/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 catWeb.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from "@react-three/drei";


export default function Model(props) {
  const { nodes, materials } = useGLTF('/catWeb.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 1, 0.76]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.Base} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.eye} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.nose} />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials['Inner ear']} />
      </group>
    </group>
  )
}

useGLTF.preload('/catWeb.glb')
