/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { PerspectiveCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/Yxubft0ox8KCDBdE/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#ebebeb']} />
      <group {...props} dispose={null}>
        <PerspectiveCamera
          name="Camera"
          makeDefault={true}
          far={100000}
          near={70}
          fov={45}
          up={[0, 1, 0]}
          position={[-499.22, 1371.81, 1732.2]}
          rotation={[-0.66, -0.11, -0.09]}
          scale={1}
        />
        <group name="Goal Pillar" position={[-154.34, 190.35, -489.36]}>
          <mesh
            name="Cube 15"
            geometry={nodes['Cube 15'].geometry}
            material={materials['Cube 15 Material']}
            castShadow
            receiveShadow
            position={[0, 81.08, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 14"
            geometry={nodes['Cube 14'].geometry}
            material={materials['Cube 14 Material']}
            castShadow
            receiveShadow
            position={[0, -81.08, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="Pillar 5" position={[-571.03, 190.42, -489.36]}>
          <mesh
            name="Cube 13"
            geometry={nodes['Cube 13'].geometry}
            material={materials['Cube 13 Material']}
            castShadow
            receiveShadow
            position={[0, 81.14, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 12"
            geometry={nodes['Cube 12'].geometry}
            material={materials['Cube 12 Material']}
            castShadow
            receiveShadow
            position={[0, -81.14, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="Pillar 4" position={[-571.03, 267.3, 67.26]}>
          <mesh
            name="Cube 11"
            geometry={nodes['Cube 11'].geometry}
            material={materials['Cube 11 Material']}
            castShadow
            receiveShadow
            position={[0, 158.03, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 10"
            geometry={nodes['Cube 10'].geometry}
            material={materials['Cube 10 Material']}
            castShadow
            receiveShadow
            position={[0, -0.36, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 8"
            geometry={nodes['Cube 8'].geometry}
            material={materials['Cube 8 Material']}
            castShadow
            receiveShadow
            position={[0, -158.03, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="Pillar 3" position={[0.71, 262.32, 67.22]}>
          <mesh
            name="Cube 9"
            geometry={nodes['Cube 9'].geometry}
            material={materials['Cube 9 Material']}
            castShadow
            receiveShadow
            position={[0.45, 153.05, -0.03]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 7"
            geometry={nodes['Cube 7'].geometry}
            material={materials['Cube 7 Material']}
            castShadow
            receiveShadow
            position={[0.45, -2.33, -0.03]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 6"
            geometry={nodes['Cube 6'].geometry}
            material={materials['Cube 6 Material']}
            castShadow
            receiveShadow
            position={[-0.45, -153.05, 0.03]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="Pillar 2" position={[0.71, 184.63, 505.23]}>
          <mesh
            name="Cube 5"
            geometry={nodes['Cube 5'].geometry}
            material={materials['Cube 5 Material']}
            castShadow
            receiveShadow
            position={[0.45, 75.36, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 4"
            geometry={nodes['Cube 4'].geometry}
            material={materials['Cube 4 Material']}
            castShadow
            receiveShadow
            position={[-0.45, -75.36, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="Pillar 1" position={[-587.91, 260.15, 505.23]}>
          <mesh
            name="Cube 3"
            geometry={nodes['Cube 3'].geometry}
            material={materials['Cube 3 Material']}
            castShadow
            receiveShadow
            position={[0, 150.87, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 2"
            geometry={nodes['Cube 2'].geometry}
            material={materials['Cube 2 Material']}
            castShadow
            receiveShadow
            position={[0, 1.16, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials['Cube Material']}
            castShadow
            receiveShadow
            position={[0, -150.87, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="cat" position={[-580.67, 622.43, 536.27]} rotation={[0, 1.44, -0.16]} scale={[0.33, 0.32, 0.35]}>
          <group name="whiskers" position={[0, -224.77, 237.4]} rotation={[0, 0, 0]} scale={2.16}>
            <mesh
              name="Subdiv 3"
              geometry={nodes['Subdiv 3'].geometry}
              material={materials.white}
              castShadow
              receiveShadow
              position={[-98.06, 33.78, 8.91]}
              rotation={[0.27, 0.05, 1.47]}
              scale={[-0.04, 1.53, 0.04]}
            />
            <mesh
              name="Subdiv 31"
              geometry={nodes['Subdiv 31'].geometry}
              material={materials.white}
              castShadow
              receiveShadow
              position={[-102.8, -0.67, -1.81]}
              rotation={[0.27, 0.09, 1.91]}
              scale={[-0.05, 1.48, 0.04]}
            />
            <mesh
              name="Subdiv 32"
              geometry={nodes['Subdiv 32'].geometry}
              material={materials.white}
              castShadow
              receiveShadow
              position={[-109.14, 17.66, 4.09]}
              rotation={[0.28, 0.06, 1.67]}
              scale={[-0.04, 1.54, 0.04]}
            />
            <mesh
              name="Subdiv copy"
              geometry={nodes['Subdiv copy'].geometry}
              material={materials.white}
              castShadow
              receiveShadow
              position={[98.06, 33.78, 8.91]}
              rotation={[0.27, -0.05, -1.47]}
              scale={[0.04, 1.53, 0.04]}
            />
            <mesh
              name="Subdiv 2"
              geometry={nodes['Subdiv 2'].geometry}
              material={materials.white}
              castShadow
              receiveShadow
              position={[102.8, -0.67, -1.81]}
              rotation={[0.27, -0.09, -1.91]}
              scale={[0.05, 1.48, 0.04]}
            />
            <mesh
              name="Subdiv copy1"
              geometry={nodes['Subdiv copy1'].geometry}
              material={materials.white}
              castShadow
              receiveShadow
              position={[109.14, 17.66, 4.09]}
              rotation={[0.28, -0.06, -1.67]}
              scale={[0.04, 1.54, 0.04]}
            />
          </group>
          <mesh
            name="eye_shine"
            geometry={nodes.eye_shine.geometry}
            material={materials['eye_shine Material']}
            castShadow
            receiveShadow
            position={[138.31, -28.03, 163.51]}
            rotation={[0.16, 0, 0]}
            scale={1.73}
          />
          <mesh
            name="eye_shine1"
            geometry={nodes.eye_shine1.geometry}
            material={materials['eye_shine1 Material']}
            castShadow
            receiveShadow
            position={[-138.31, -28.03, 163.51]}
            rotation={[0.16, 0, 0]}
            scale={1.73}
          />
          <mesh
            name="eye"
            geometry={nodes.eye.geometry}
            material={materials.black}
            castShadow
            receiveShadow
            position={[-110.08, -48.18, 131.41]}
            rotation={[0.16, 0, 0]}
            scale={1.73}
          />
          <mesh
            name="nose"
            geometry={nodes.nose.geometry}
            material={materials.black}
            castShadow
            receiveShadow
            position={[4.91, -140.13, 248]}
            rotation={[-0.08, 0, 0]}
            scale={[1.58, 1.45, 1.58]}
          />
          <mesh
            name="head"
            geometry={nodes.head.geometry}
            material={materials.grey}
            castShadow
            receiveShadow
            position={[-47.04, -82.66, -80.35]}
            rotation={[0.16, 0, 0]}
            scale={[1.35, 1.43, 1.3]}
          />
          <mesh
            name="eye1"
            geometry={nodes.eye1.geometry}
            material={materials.black}
            castShadow
            receiveShadow
            position={[116.33, -48.18, 131.41]}
            rotation={[0.16, 0, 0]}
            scale={1.73}
          />
          <mesh
            name="ear_inside"
            geometry={nodes.ear_inside.geometry}
            material={materials.red}
            castShadow
            receiveShadow
            position={[-105.19, 42.22, -45.99]}
            rotation={[0.27, -0.27, -0.61]}
            scale={[2.48, 1.64, 1.36]}
          />
          <mesh
            name="ear"
            geometry={nodes.ear.geometry}
            material={materials.grey}
            castShadow
            receiveShadow
            position={[-106.54, 148.59, -101.98]}
            rotation={[0.27, -0.35, 0.22]}
            scale={[-2, 2.35, 2.41]}
          />
          <mesh
            name="ear_inside1"
            geometry={nodes.ear_inside1.geometry}
            material={materials.red}
            castShadow
            receiveShadow
            position={[115.53, 42.22, -45.99]}
            rotation={[0.27, 0.27, 0.61]}
            scale={[-2.45, 1.63, 1.35]}
          />
          <mesh
            name="ear1"
            geometry={nodes.ear1.geometry}
            material={materials.grey}
            castShadow
            receiveShadow
            position={[116.85, 148.59, -101.98]}
            rotation={[0.27, 0.34, -0.22]}
            scale={[1.97, 2.35, 2.4]}
          />
          <mesh
            name="mouth"
            geometry={nodes.mouth.geometry}
            material={materials.black}
            castShadow
            receiveShadow
            position={[4.67, -193.8, 198.84]}
            rotation={[0.22, 0.01, 0]}
            scale={[4.02, 0.09, 1.25]}
          />
        </group>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1000}
          shadow-camera-right={1000}
          shadow-camera-top={1000}
          shadow-camera-bottom={-1000}
          position={[-91.41, 461.69, 300]}
        />
        <mesh
          name="Floor"
          geometry={nodes.Floor.geometry}
          material={materials['Floor Material']}
          castShadow
          receiveShadow
          position={[-192.53, 13.36, 76.89]}
          scale={[3, 1, 3.86]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}
